spring:
  application:
    name: conference_system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gittestsql
    username: root
    password: mysql94
    hikari:
      max-lifetime: 1800000 # 30min
